import fs from 'fs-extra';
import os from 'os';
import path from 'path';
import R from 'ramda';

import GitClient from '@src/clients/git-client';
import ResourcesConfig, { getResourcesConfig } from '@src/model/resources-config';
import * as CONSTANTS from '@src/utils/constants';
import Messenger from '@src/view/messenger';
import SpinnerView from '@src/view/spinner-view';

const filesToIgnore = ['lambda/node_modules', '.ask/', 'ask-resources.json'];

/**
 * To generate local skill project folder and ask-resources.json
 * @param {string} projectPath The skill project folder path
 * @param {string} skillId The skill id
 * @param {string} skillName The skill name
 * @param {JSON} metadata The Alexa hosted skill metadata
 * @param {string} profile The current profile
 */
function generateProject(projectPath: string, skillId: string, skillName: string, metadata: any, profile: string) {
    _generateProjectDirectory(projectPath);
    _updateAskResources(projectPath, skillId, metadata, profile);
    Messenger.getInstance().info(`\nProject directory for ${skillName} created at\n\t${projectPath}`);
}

function _generateProjectDirectory(projectPath: string) {
    const askResourcesPath = path.join(projectPath, CONSTANTS.FILE_PATH.ASK_RESOURCES_JSON_CONFIG);
    const askResourcesJson = R.clone((ResourcesConfig as any).BASE);
    fs.mkdirSync(projectPath);
    fs.writeJSONSync(askResourcesPath, askResourcesJson, { spaces: CONSTANTS.CONFIGURATION.JSON_DISPLAY_INDENT });
}

function _updateAskResources(projectPath: string, skillId: string, metadata: any, profile: string) {
    new ResourcesConfig(path.join(projectPath, CONSTANTS.FILE_PATH.ASK_RESOURCES_JSON_CONFIG));
    getResourcesConfig().setSkillId(profile, skillId);
    getResourcesConfig().setSkillInfraType(profile, '@ask-cli/hosted-skill-deployer');
    getResourcesConfig().write();
}

/**
 * To go through the git clone process to get the project from git repository
 * @param {string} projectPath The skill project folder path
 * @param {string} skillId The skill Id
 * @param {string} skillName The skill name
 * @param {string} profile The current profile
 * @param {string} repositoryUrl The git url
 * @param {boolean} doDebug is debug mode or not
 */
function cloneProjectFromGit(projectPath: string, skillId: string, skillName: string, profile: string, repositoryUrl: string, doDebug: boolean) {
    const verbosityOptions = {
        showCommand: !!doDebug,
        showOutput: !!doDebug
    };
    _gitCloneWorkflow(projectPath, repositoryUrl, verbosityOptions, skillId, profile);
    Messenger.getInstance().info(`\nLambda code for ${skillName} created at\n\t./lambda`);
}

function _gitCloneWorkflow(projectPath: string, repositoryUrl: string, verbosityOptions: any, skillId: string, profile: string) {
    const verbose = verbosityOptions.showCommand;
    const progressSpinner = new SpinnerView();
    if (!verbose) {
        progressSpinner.start('Cloning Alexa Hosted Skill...');
    }

    if (verbose) {
        Messenger.getInstance().info('- Setting up git repo...');
    }
    const gitClient = new GitClient(projectPath, verbosityOptions);
    gitClient.init();
    const credentialScriptPath = path.join(os.homedir(),
        CONSTANTS.FILE_PATH.ASK.HIDDEN_FOLDER,
        CONSTANTS.FILE_PATH.ASK.SCRIPTS_FOLDER.NAME,
        CONSTANTS.FILE_PATH.ASK.SCRIPTS_FOLDER.GIT_CREDENTIAL_HELPER);
    const credentialScriptExecution = `'${credentialScriptPath}' ${profile} ${skillId}`;
    gitClient.configureCredentialHelper(credentialScriptExecution, repositoryUrl);
    gitClient.addOrigin(repositoryUrl);

    if (verbose) {
        Messenger.getInstance().info('- Fetching git repo...');
    }
    // The original passed projectPath and verbosityOptions as params, but fetchAll() takes 0 args.
    gitClient.fetchAll();

    if (verbose) {
        Messenger.getInstance().info('- Checking out master branch...');
    }
    gitClient.checkoutBranch('master');

    if (verbose) {
        Messenger.getInstance().info('- Setting up .gitignore...');
    }

    gitClient.setupGitIgnore(filesToIgnore);

    if (verbose) {
        Messenger.getInstance().info('- Git repo successfully setup');
    }
    _makeBranchesVisible(gitClient);

    if (!verbose) {
        progressSpinner.terminate();
    }
}

function _makeBranchesVisible(gitClient: GitClient) {
    const branchesToCheckout = ['prod', 'master'];
    branchesToCheckout.forEach((branch) => {
        gitClient.checkoutBranch(branch);
    });
}

/**
 * To check whether a skill-package folder exists,
 * it can be generated by collecting git-cloned skill.json, models and isps.
 * otherwise, return false.
 * @param {string} skillName The skill name
 * @param {string} projectPath The skill project folder path
 * @param {string} skillId The skill id
 * @param {callback} callback { error, response }
 */
function doSkillPackageExist(skillName: string, projectPath: string, skillId: string, callback: Function) {
    const skillPackagePath = path.join(projectPath, 'skill-package');
    if (fs.existsSync(skillPackagePath)) {
        return callback(null, true);
    }
    fs.mkdirSync(skillPackagePath);
    const modelsPath = path.join(projectPath, 'models');
    const skillJsonPath = path.join(projectPath, 'skill.json');
    const ispsPath = path.join(projectPath, 'isps');
    const doModelsExist = fs.existsSync(modelsPath);
    const doSkillJsonExist = fs.existsSync(skillJsonPath);
    const doIspsExist = fs.existsSync(ispsPath);
    if (!(doModelsExist || doSkillJsonExist)) {
        return callback(null, false);
    }
    if (doModelsExist) {
        fs.moveSync(modelsPath, path.join(skillPackagePath, 'interactionModels/custom'));
    }
    if (doSkillJsonExist) {
        fs.moveSync(skillJsonPath, path.join(skillPackagePath, 'skill.json'));
    }
    if (doIspsExist) {
        fs.moveSync(skillJsonPath, path.join(skillPackagePath, 'isps'));
    }
    callback(null, true);
}

export default {
    generateProject,
    cloneProjectFromGit,
    doSkillPackageExist
};
